REM Build Bat File
REM Precheck the Resource 
"C:\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\mreapp\TelnetVXP\TelnetVXP.vcproj"
REM Copmile c file 
"C:\SourceryLite\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\mreapp\TelnetVXP\arm\gccmain.o" -c "C:\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\mreapp\TelnetVXP\include" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\ResID" -I "D:\mreapp\TelnetVXP\src\app\widget" -I "D:\mreapp\TelnetVXP\src\app\launcher" -I "D:\mreapp\TelnetVXP\src\app\wallpaper" -I "D:\mreapp\TelnetVXP\src\app\screen_lock" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\src\framework" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\base" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\mvc" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\pme" -I "D:\mreapp\TelnetVXP\src\framework\mmi_core" -I "D:\mreapp\TelnetVXP\src\ui_engine\vrt\interface" -I "D:\mreapp\TelnetVXP\src\component" -I "D:\mreapp\TelnetVXP\src\ui_engine\framework\xml" -I "D:\mreapp\TelnetVXP"
REM Copmile c file 
"C:\SourceryLite\Bin\arm-none-eabi-g++" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions           -fcheck-new -o "D:\mreapp\TelnetVXP\arm\Console.o" -c "d:\mreapp\TelnetVXP\Console.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\mreapp\TelnetVXP\include" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\ResID" -I "D:\mreapp\TelnetVXP\src\app\widget" -I "D:\mreapp\TelnetVXP\src\app\launcher" -I "D:\mreapp\TelnetVXP\src\app\wallpaper" -I "D:\mreapp\TelnetVXP\src\app\screen_lock" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\src\framework" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\base" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\mvc" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\pme" -I "D:\mreapp\TelnetVXP\src\framework\mmi_core" -I "D:\mreapp\TelnetVXP\src\ui_engine\vrt\interface" -I "D:\mreapp\TelnetVXP\src\component" -I "D:\mreapp\TelnetVXP\src\ui_engine\framework\xml" -I "D:\mreapp\TelnetVXP"
REM Copmile c file 
"C:\SourceryLite\Bin\arm-none-eabi-g++" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions           -fcheck-new           -fcheck-new -o "D:\mreapp\TelnetVXP\arm\Consone.o" -c "d:\mreapp\TelnetVXP\Consone.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\mreapp\TelnetVXP\include" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\ResID" -I "D:\mreapp\TelnetVXP\src\app\widget" -I "D:\mreapp\TelnetVXP\src\app\launcher" -I "D:\mreapp\TelnetVXP\src\app\wallpaper" -I "D:\mreapp\TelnetVXP\src\app\screen_lock" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\src\framework" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\base" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\mvc" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\pme" -I "D:\mreapp\TelnetVXP\src\framework\mmi_core" -I "D:\mreapp\TelnetVXP\src\ui_engine\vrt\interface" -I "D:\mreapp\TelnetVXP\src\component" -I "D:\mreapp\TelnetVXP\src\ui_engine\framework\xml" -I "D:\mreapp\TelnetVXP"
REM Copmile c file 
"C:\SourceryLite\Bin\arm-none-eabi-g++" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions           -fcheck-new           -fcheck-new           -fcheck-new -o "D:\mreapp\TelnetVXP\arm\TelnetVXP.o" -c "d:\mreapp\TelnetVXP\TelnetVXP.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "C:\MRE_SDK\include" -I "C:\MRE_SDK\include\service" -I "D:\mreapp\TelnetVXP\include" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\ResID" -I "D:\mreapp\TelnetVXP\src\app\widget" -I "D:\mreapp\TelnetVXP\src\app\launcher" -I "D:\mreapp\TelnetVXP\src\app\wallpaper" -I "D:\mreapp\TelnetVXP\src\app\screen_lock" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\include\component" -I "D:\mreapp\TelnetVXP\include\service" -I "D:\mreapp\TelnetVXP\src\framework" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\base" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\mvc" -I "D:\mreapp\TelnetVXP\src\framework\ui_core\pme" -I "D:\mreapp\TelnetVXP\src\framework\mmi_core" -I "D:\mreapp\TelnetVXP\src\ui_engine\vrt\interface" -I "D:\mreapp\TelnetVXP\src\component" -I "D:\mreapp\TelnetVXP\src\ui_engine\framework\xml" -I "D:\mreapp\TelnetVXP"
REM Link app 
"C:\SourceryLite\Bin\arm-none-eabi-gcc" -o "D:\mreapp\TelnetVXP\TelnetVXP.axf"  "D:\mreapp\TelnetVXP\arm\gccmain.o"  "D:\mreapp\TelnetVXP\arm\Console.o"  "D:\mreapp\TelnetVXP\arm\Consone.o"  "D:\mreapp\TelnetVXP\arm\TelnetVXP.o" -fpic -msvr4-struct-return -pie  -T "C:\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\pertcp.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\persensor.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\persmsper.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\perbitstream.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\perfile.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\perhttp.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\perpro.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\persec.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\MRE_SDK\lib\MRE30\armgcc_t\perudp.a"
REM Pack resource to app 
"C:\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\mreapp\TelnetVXP\TelnetVXP.pkd" -e AXF "D:\mreapp\TelnetVXP\TelnetVXP.vcproj" "D:\mreapp\TelnetVXP\TelnetVXP.axf"
REM Add tag infromation 
"C:\MRE_SDK\tools\PackDigist.exe" "D:\mreapp\TelnetVXP\TelnetVXP.vcproj" "TelnetVXP" "0.1.0" "Ximik_Boda" "500" "NotSupportBg" "Not Support rotate" "TelnetVXP" "TelnetVXP" "TelnetVXP" "1234567890" "content" " TCP Sensor SMS(person) BitStream File HTTP ProMng Sec SysStorage UDP" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\mreapp\TelnetVXP\arm D:\mreapp\TelnetVXP\build.log

